# coding: utf-8

# flake8: noqa

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.16"

# import apis into sdk package
from workplace_client.api.available_packages_api import AvailablePackagesApi
from workplace_client.api.change_quota_api import ChangeQuotaApi
from workplace_client.api.create_alias_api import CreateAliasApi
from workplace_client.api.delete_alias_api import DeleteAliasApi
from workplace_client.api.delete_email_api import DeleteEmailApi
from workplace_client.api.dns_info_api import DnsInfoApi
from workplace_client.api.domain_api import DomainApi
from workplace_client.api.domain_alias_api import DomainAliasApi
from workplace_client.api.domain_info_api import DomainInfoApi
from workplace_client.api.get_token_api import GetTokenApi
from workplace_client.api.import_api import ImportApi
from workplace_client.api.refresh_token_api import RefreshTokenApi
from workplace_client.api.reset_password_api import ResetPasswordApi
from workplace_client.api.subscription_info_api import SubscriptionInfoApi
from workplace_client.api.subscriptions_api import SubscriptionsApi
from workplace_client.api.upgrade_api import UpgradeApi

# import ApiClient
from workplace_client.api_response import ApiResponse
from workplace_client.api_client import ApiClient
from workplace_client.configuration import Configuration
from workplace_client.exceptions import OpenApiException
from workplace_client.exceptions import ApiTypeError
from workplace_client.exceptions import ApiValueError
from workplace_client.exceptions import ApiKeyError
from workplace_client.exceptions import ApiAttributeError
from workplace_client.exceptions import ApiException

# import models into sdk package
from workplace_client.models.alias_display import AliasDisplay
from workplace_client.models.change_email_quota import ChangeEmailQuota
from workplace_client.models.delete_alias import DeleteAlias
from workplace_client.models.delete_email import DeleteEmail
from workplace_client.models.dns_info_request import DnsInfoRequest
from workplace_client.models.dns_info_response import DnsInfoResponse
from workplace_client.models.dns_record import DnsRecord
from workplace_client.models.domain import Domain
from workplace_client.models.domain_action import DomainAction
from workplace_client.models.email_alias import EmailAlias
from workplace_client.models.email_display import EmailDisplay
from workplace_client.models.found_dns_records import FoundDnsRecords
from workplace_client.models.open_exchange_create_account import OpenExchangeCreateAccount
from workplace_client.models.order_display import OrderDisplay
from workplace_client.models.password_reset import PasswordReset
from workplace_client.models.service_action import ServiceAction
from workplace_client.models.standard_response import StandardResponse
from workplace_client.models.sub_scription_info import SubScriptionInfo
from workplace_client.models.subscription_details import SubscriptionDetails
from workplace_client.models.subscription_info_response import SubscriptionInfoResponse
from workplace_client.models.subscription_usage_response import SubscriptionUsageResponse
from workplace_client.models.subscriptions_read_response import SubscriptionsReadResponse
from workplace_client.models.token_obtain_pair import TokenObtainPair
from workplace_client.models.token_refresh import TokenRefresh
