# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.workplace_create_emails import WorkplaceCreateEmails

class TestWorkplaceCreateEmails(unittest.TestCase):
    """WorkplaceCreateEmails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkplaceCreateEmails:
        """Test WorkplaceCreateEmails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkplaceCreateEmails`
        """
        model = WorkplaceCreateEmails()
        if include_optional:
            return WorkplaceCreateEmails(
                emails = [
                    '0'
                    ],
                domain_name = '0',
                subscription = 0,
                new_subscription = True,
                display_name = '0',
                user_password = '0',
                email_quota = 0,
                client_id = 0
            )
        else:
            return WorkplaceCreateEmails(
                emails = [
                    '0'
                    ],
                domain_name = '0',
                subscription = 0,
                new_subscription = True,
                display_name = '0',
                user_password = '0',
                email_quota = 0,
                client_id = 0,
        )
        """

    def testWorkplaceCreateEmails(self):
        """Test WorkplaceCreateEmails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
