# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.update_email_quota_api import UpdateEmailQuotaApi


class TestUpdateEmailQuotaApi(unittest.TestCase):
    """UpdateEmailQuotaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpdateEmailQuotaApi()

    def tearDown(self) -> None:
        pass

    def test_update_email_quota(self) -> None:
        """Test case for update_email_quota

        Update email quota
        """
        pass


if __name__ == '__main__':
    unittest.main()
