# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.subscription_info_api import SubscriptionInfoApi


class TestSubscriptionInfoApi(unittest.TestCase):
    """SubscriptionInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionInfoApi()

    def tearDown(self) -> None:
        pass

    def test_subscription_info_create(self) -> None:
        """Test case for subscription_info_create

        Get subscription usage info.
        """
        pass


if __name__ == '__main__':
    unittest.main()
