# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dns_info_api import DnsInfoApi


class TestDnsInfoApi(unittest.TestCase):
    """DnsInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DnsInfoApi()

    def tearDown(self) -> None:
        pass

    def test_dns_info_create(self) -> None:
        """Test case for dns_info_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
