# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.change_quota_api import ChangeQuotaApi


class TestChangeQuotaApi(unittest.TestCase):
    """ChangeQuotaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChangeQuotaApi()

    def tearDown(self) -> None:
        pass

    def test_change_quota_create(self) -> None:
        """Test case for change_quota_create

        Change email quota.
        """
        pass


if __name__ == '__main__':
    unittest.main()
