# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.dns_info_create200_response import DnsInfoCreate200Response

class TestDnsInfoCreate200Response(unittest.TestCase):
    """DnsInfoCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsInfoCreate200Response:
        """Test DnsInfoCreate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsInfoCreate200Response`
        """
        model = DnsInfoCreate200Response()
        if include_optional:
            return DnsInfoCreate200Response(
                score = 1.337,
                message = '',
                domain = '',
                all_dns_score = 1.337,
                found = 1.337,
                total = 1.337,
                missing_dns = [
                    None
                    ],
                other_missing_dns = [
                    None
                    ],
                found_dns = None,
                error = [
                    ''
                    ]
            )
        else:
            return DnsInfoCreate200Response(
                score = 1.337,
        )
        """

    def testDnsInfoCreate200Response(self):
        """Test DnsInfoCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
