# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.create_alias_api import CreateAliasApi


class TestCreateAliasApi(unittest.TestCase):
    """CreateAliasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreateAliasApi()

    def tearDown(self) -> None:
        pass

    def test_create_alias_create(self) -> None:
        """Test case for create_alias_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
