# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.reset_password_api import ResetPasswordApi


class TestResetPasswordApi(unittest.TestCase):
    """ResetPasswordApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ResetPasswordApi()

    def tearDown(self) -> None:
        pass

    def test_reset_password_create(self) -> None:
        """Test case for reset_password_create

        Reset subscription email password.
        """
        pass


if __name__ == '__main__':
    unittest.main()
