# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.available_packages_api import AvailablePackagesApi


class TestAvailablePackagesApi(unittest.TestCase):
    """AvailablePackagesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AvailablePackagesApi()

    def tearDown(self) -> None:
        pass

    def test_available_packages_list(self) -> None:
        """Test case for available_packages_list

        Get available subscriptions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
