# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.found_dns_records import FoundDnsRecords

class TestFoundDnsRecords(unittest.TestCase):
    """FoundDnsRecords unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FoundDnsRecords:
        """Test FoundDnsRecords
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FoundDnsRecords`
        """
        model = FoundDnsRecords()
        if include_optional:
            return FoundDnsRecords(
                ns = [
                    ''
                    ],
                a = [
                    ''
                    ],
                aaaa = [
                    ''
                    ],
                cname = [
                    ''
                    ],
                mx = [
                    ''
                    ],
                txt = [
                    ''
                    ],
                soa = [
                    ''
                    ],
                srv = [
                    ''
                    ],
                ptr = [
                    ''
                    ]
            )
        else:
            return FoundDnsRecords(
        )
        """

    def testFoundDnsRecords(self):
        """Test FoundDnsRecords"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
