# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_console_client.api.delete_email_api import DeleteEmailApi


class TestDeleteEmailApi(unittest.TestCase):
    """DeleteEmailApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeleteEmailApi()

    def tearDown(self) -> None:
        pass

    def test_delete_email_create(self) -> None:
        """Test case for delete_email_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
