# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.subscriptions_read200_response import SubscriptionsRead200Response

class TestSubscriptionsRead200Response(unittest.TestCase):
    """SubscriptionsRead200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionsRead200Response:
        """Test SubscriptionsRead200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionsRead200Response`
        """
        model = SubscriptionsRead200Response()
        if include_optional:
            return SubscriptionsRead200Response(
                domain_context = None,
                user_emails = [
                    None
                    ],
                email_aliases = None
            )
        else:
            return SubscriptionsRead200Response(
        )
        """

    def testSubscriptionsRead200Response(self):
        """Test SubscriptionsRead200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
