# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.change_quota_create200_response import ChangeQuotaCreate200Response

class TestChangeQuotaCreate200Response(unittest.TestCase):
    """ChangeQuotaCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChangeQuotaCreate200Response:
        """Test ChangeQuotaCreate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChangeQuotaCreate200Response`
        """
        model = ChangeQuotaCreate200Response()
        if include_optional:
            return ChangeQuotaCreate200Response(
                message = '',
                error = ''
            )
        else:
            return ChangeQuotaCreate200Response(
        )
        """

    def testChangeQuotaCreate200Response(self):
        """Test ChangeQuotaCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
