# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.get_token_api import GetTokenApi


class TestGetTokenApi(unittest.TestCase):
    """GetTokenApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GetTokenApi()

    def tearDown(self) -> None:
        pass

    def test_get_token_create(self) -> None:
        """Test case for get_token_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
