# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_console_client.models.dns_info_create200_response import DnsInfoCreate200Response

class TestDnsInfoCreate200Response(unittest.TestCase):
    """DnsInfoCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsInfoCreate200Response:
        """Test DnsInfoCreate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsInfoCreate200Response`
        """
        model = DnsInfoCreate200Response()
        if include_optional:
            return DnsInfoCreate200Response(
                score = 56,
                message = ''
            )
        else:
            return DnsInfoCreate200Response(
        )
        """

    def testDnsInfoCreate200Response(self):
        """Test DnsInfoCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
