# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.subscription_info_create200_response import SubscriptionInfoCreate200Response

class TestSubscriptionInfoCreate200Response(unittest.TestCase):
    """SubscriptionInfoCreate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionInfoCreate200Response:
        """Test SubscriptionInfoCreate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionInfoCreate200Response`
        """
        model = SubscriptionInfoCreate200Response()
        if include_optional:
            return SubscriptionInfoCreate200Response(
                used_emails = 1.337,
                remaining_quota = 1.337,
                remaining_emails = 1.337,
                allowed_emails = 1.337,
                allowed_alias = 1.337,
                remaining_alias = 1.337,
                allowed_quota = 1.337
            )
        else:
            return SubscriptionInfoCreate200Response(
        )
        """

    def testSubscriptionInfoCreate200Response(self):
        """Test SubscriptionInfoCreate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
