# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.dns_info_create_request import DnsInfoCreateRequest

class TestDnsInfoCreateRequest(unittest.TestCase):
    """DnsInfoCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DnsInfoCreateRequest:
        """Test DnsInfoCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DnsInfoCreateRequest`
        """
        model = DnsInfoCreateRequest()
        if include_optional:
            return DnsInfoCreateRequest(
                domain = '',
                client_id = '',
                email = ''
            )
        else:
            return DnsInfoCreateRequest(
                domain = '',
                client_id = '',
                email = '',
        )
        """

    def testDnsInfoCreateRequest(self):
        """Test DnsInfoCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
