# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_console_client.api.available_subscriptions_api import AvailableSubscriptionsApi


class TestAvailableSubscriptionsApi(unittest.TestCase):
    """AvailableSubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AvailableSubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_available_subscriptions_list(self) -> None:
        """Test case for available_subscriptions_list

        Get available subscriptions.
        """
        pass


if __name__ == '__main__':
    unittest.main()
