# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_console_client.api.domain_alias_api import DomainAliasApi


class TestDomainAliasApi(unittest.TestCase):
    """DomainAliasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainAliasApi()

    def tearDown(self) -> None:
        pass

    def test_domain_alias_create(self) -> None:
        """Test case for domain_alias_create

        """
        pass


if __name__ == '__main__':
    unittest.main()
