# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_subscriptions_create(self) -> None:
        """Test case for subscriptions_create

        Create a new email subscription, it will create a new subscription for the domain if emails list is not empty
        """
        pass

    def test_subscriptions_list(self) -> None:
        """Test case for subscriptions_list

        """
        pass

    def test_subscriptions_read(self) -> None:
        """Test case for subscriptions_read

        Get subscription details
        """
        pass

    def test_update_subscription_status(self) -> None:
        """Test case for update_subscription_status

        Update subscription status, delete, suspend, unsuspend, etc...
        """
        pass


if __name__ == '__main__':
    unittest.main()
