# coding: utf-8

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_subscriptions_create(self) -> None:
        """Test case for subscriptions_create

        """
        pass

    def test_subscriptions_create_0(self) -> None:
        """Test case for subscriptions_create_0

        """
        pass

    def test_subscriptions_list(self) -> None:
        """Test case for subscriptions_list

        """
        pass

    def test_subscriptions_read(self) -> None:
        """Test case for subscriptions_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
