# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.subscription_details import SubscriptionDetails

class TestSubscriptionDetails(unittest.TestCase):
    """SubscriptionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubscriptionDetails:
        """Test SubscriptionDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubscriptionDetails`
        """
        model = SubscriptionDetails()
        if include_optional:
            return SubscriptionDetails(
                id = 56,
                name = '0',
                mailbox = -2147483648,
                quota = -2147483648,
                alias = -2147483648,
                forward = -2147483648,
                platform = 'whmcs',
                price = ''
            )
        else:
            return SubscriptionDetails(
                name = '0',
        )
        """

    def testSubscriptionDetails(self):
        """Test SubscriptionDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
