# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.domain_info_api import DomainInfoApi


class TestDomainInfoApi(unittest.TestCase):
    """DomainInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DomainInfoApi()

    def tearDown(self) -> None:
        pass

    def test_domain_info_create(self) -> None:
        """Test case for domain_info_create

        Get domain subscription details.
        """
        pass


if __name__ == '__main__':
    unittest.main()
