# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.api.delete_alias_api import DeleteAliasApi


class TestDeleteAliasApi(unittest.TestCase):
    """DeleteAliasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeleteAliasApi()

    def tearDown(self) -> None:
        pass

    def test_delete_alias_create(self) -> None:
        """Test case for delete_alias_create

        Delete alias.
        """
        pass


if __name__ == '__main__':
    unittest.main()
