# coding: utf-8

"""
    Workplace Console API

    API for managing email and workplace service subscriptions.

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from workplace_client.models.email_display import EmailDisplay

class TestEmailDisplay(unittest.TestCase):
    """EmailDisplay unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmailDisplay:
        """Test EmailDisplay
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmailDisplay`
        """
        model = EmailDisplay()
        if include_optional:
            return EmailDisplay(
                id = 56,
                name = '0',
                email_quota = -2147483648,
                max_quota = -2147483648,
                used_quota = -2147483648,
                email_id = -2147483648,
                display_name = '',
                order = 56
            )
        else:
            return EmailDisplay(
                name = '0',
        )
        """

    def testEmailDisplay(self):
        """Test EmailDisplay"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
