# coding: utf-8

# flake8: noqa
"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.token_obtain_pair import TokenObtainPair
from openapi_client.models.token_refresh import TokenRefresh
