# coding: utf-8

# flake8: noqa

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from workplace_console_client.api.change_quota_api import ChangeQuotaApi
from workplace_console_client.api.create_alias_api import CreateAliasApi
from workplace_console_client.api.delete_alias_api import DeleteAliasApi
from workplace_console_client.api.delete_email_api import DeleteEmailApi
from workplace_console_client.api.dns_info_api import DnsInfoApi
from workplace_console_client.api.domain_api import DomainApi
from workplace_console_client.api.domain_alias_api import DomainAliasApi
from workplace_console_client.api.domain_info_api import DomainInfoApi
from workplace_console_client.api.get_token_api import GetTokenApi
from workplace_console_client.api.import_api import ImportApi
from workplace_console_client.api.refresh_token_api import RefreshTokenApi
from workplace_console_client.api.reset_password_api import ResetPasswordApi
from workplace_console_client.api.subscription_info_api import SubscriptionInfoApi
from workplace_console_client.api.subscriptions_api import SubscriptionsApi
from workplace_console_client.api.upgrade_api import UpgradeApi

# import ApiClient
from workplace_console_client.api_response import ApiResponse
from workplace_console_client.api_client import ApiClient
from workplace_console_client.configuration import Configuration
from workplace_console_client.exceptions import OpenApiException
from workplace_console_client.exceptions import ApiTypeError
from workplace_console_client.exceptions import ApiValueError
from workplace_console_client.exceptions import ApiKeyError
from workplace_console_client.exceptions import ApiAttributeError
from workplace_console_client.exceptions import ApiException

# import models into sdk package
from workplace_console_client.models.dns_info_create200_response import DnsInfoCreate200Response
from workplace_console_client.models.dns_info_create_request import DnsInfoCreateRequest
from workplace_console_client.models.token_obtain_pair import TokenObtainPair
from workplace_console_client.models.token_refresh import TokenRefresh
