# coding: utf-8

# flake8: noqa

"""
    Open Xchange Console

    Test description

    The version of the OpenAPI document: v1
    Contact: support@truehost.cloud
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.change_quota_api import ChangeQuotaApi
from openapi_client.api.create_alias_api import CreateAliasApi
from openapi_client.api.delete_alias_api import DeleteAliasApi
from openapi_client.api.delete_email_api import DeleteEmailApi
from openapi_client.api.dns_info_api import DnsInfoApi
from openapi_client.api.domain_api import DomainApi
from openapi_client.api.domain_alias_api import DomainAliasApi
from openapi_client.api.domain_info_api import DomainInfoApi
from openapi_client.api.get_token_api import GetTokenApi
from openapi_client.api.import_api import ImportApi
from openapi_client.api.refresh_token_api import RefreshTokenApi
from openapi_client.api.reset_password_api import ResetPasswordApi
from openapi_client.api.subscription_info_api import SubscriptionInfoApi
from openapi_client.api.subscriptions_api import SubscriptionsApi
from openapi_client.api.upgrade_api import UpgradeApi

# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.api_client import ApiClient
from openapi_client.configuration import Configuration
from openapi_client.exceptions import OpenApiException
from openapi_client.exceptions import ApiTypeError
from openapi_client.exceptions import ApiValueError
from openapi_client.exceptions import ApiKeyError
from openapi_client.exceptions import ApiAttributeError
from openapi_client.exceptions import ApiException

# import models into sdk package
from openapi_client.models.token_obtain_pair import TokenObtainPair
from openapi_client.models.token_refresh import TokenRefresh
